# Generated by Django 2.0.6 on 2018-07-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180703_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='zip_code',
            field=models.CharField(default='66506', max_length=5, verbose_name='zip code'),
        ),
    ]
