# Generated by Django 2.0.6 on 2018-07-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180705_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
    ]
