# Generated by Django 2.0.6 on 2018-07-05 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180705_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ContactInformation'),
        ),
    ]
