# Generated by Django 2.0.6 on 2018-07-07 07:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180707_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to=users.models.userpath),
        ),
    ]
